package com.daomainfiles;
import java.io.BufferedReader;
import java.io.InputStreamReader;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

import com.pojo_orm_classes.TwoWheeler_Pojo;
import com.pojo_orm_classes.FourWheeler_Pojo;

public class inheritancemapping_tableper {

	public static void main(String[] args) throws Exception {
SessionFactory sessionFactory = new Configuration().configure("hibernatedb.cfg.xml").buildSessionFactory();//transient life cycle state
		
		Session s = sessionFactory.openSession();// create a session object
		Transaction t=s.beginTransaction();
		
		FourWheeler_Pojo e2=new FourWheeler_Pojo();    
		TwoWheeler_Pojo e3=new TwoWheeler_Pojo();

		InputStreamReader i = new InputStreamReader(System.in);
		BufferedReader b = new BufferedReader(i);

		//NO NEED TO READ THE EMPNO... BCOS IT IS AUTOGENERATED VALUE!

		System.out.println("Four Wheeler:::  ");
		System.out.println("FName: ");
		String name1 = b.readLine();
		System.out.println("License Number: ");
		int s1=Integer.parseInt(b.readLine());
		System.out.println("SteeringWheel Type: ");
		String steeringwheel1 = b.readLine();

		e2.setName(name1);
		e2.setLicenseNumber(s1);
		e2.setSteeringWheel(steeringwheel1);

		System.out.println("Two Wheeler:::  ");
		System.out.println("TName: ");
		String name11 = b.readLine();
		System.out.println("License Number: ");
		int s2=Integer.parseInt(b.readLine());
		System.out.println("SteeringHandle Type: ");
		String steeringhandle1 = b.readLine();

		e3.setName(name11);
		e3.setLicenseNumber(s2);
		e3.setSteeringHandle(steeringhandle1);

		//all the e2(subclass) and e3(subclass) objects are stored in a single table
		s.persist(e2);//persisting permanant employee
		s.persist(e3);//persisting contract employee
		System.out.println("*****Inserted*****");
		t.commit();//commit or save the query

		/*
		 * We can see NULL values are stored in 
		 * pay_per_day and contract_duration column for PermanentEmployees 
		 * and 
		 * NULL values is stored in perm_salary and perm_incentive column for ContractEmployees.
		 */
		s.close();//detached state


	}

}